ALTER TABLE Vocab
ALTER COLUMN sino_vi VARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN audio_path VARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN image_path VARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN ex_sentence VARCHAR(MAX) NOT NULL;

ALTER TABLE Vocab
ALTER COLUMN ex_sentence_meaning VARCHAR(MAX) NOT NULL;

ALTER TABLE Vocab
ALTER COLUMN meaning VARCHAR(MAX) NOT NULL;