ALTER TABLE Vocab
ALTER COLUMN sino_vi NVARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN audio_path NVARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN image_path NVARCHAR(100) NULL;

ALTER TABLE Vocab
ALTER COLUMN ex_sentence NVARCHAR(MAX) NOT NULL;

ALTER TABLE Vocab
ALTER COLUMN ex_sentence_meaning NVARCHAR(MAX) NOT NULL;

ALTER TABLE Vocab
ALTER COLUMN meaning NVARCHAR(MAX) NOT NULL;